name: ci
on: [push]

permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v2
        with:
          client-id: dd1efe98-399e-4fb5-b5f4-2d0f0bfd525b
          tenant-id: 90eaef6b-3882-4c51-8467-1155649bc19d
          subscription-id: fbac4321-0f41-46f0-baea-f23a62385eb5
   

      - name: Run Hello World
        run: echo "Hello from self-hosted runner!"
     
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.13.1   # ya latest
     
      - name: Terraform Init
        run: terraform init -backend-config="resource_group_name=uday-rg" `
                             -backend-config="storage_account_name=terraformuday7231" `
                             -backend-config="container_name=tfstatefile" `
                             -backend-config="key=prod.tfstate"
        working-directory: ./infra
      
      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ./infra
        
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
        working-directory: ./infra
