name: ci
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main 

permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v2
        with:
          clientid: dd1efe98-399e-4fb5-b5f4-2d0f0bfd525b
          tenantid: 90eaef6b-3882-4c51-8467-1155649bc19d
          subscriptionid: fbac4321-0f41-46f0-baea-f23a62385eb5
          auth-type: "id-token"
          working-directory: infra
   

      - name: Run Hello World
        run: echo "Hello from self-hosted runner!"
     
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.13.1   # ya latest

      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Terraform Init
        run: terraform init
        working-directory: infra
        shell: powershell
      - name: Terraform Plan

        id: plan

        run: terraform plan -no-color -input=false

        continue-on-error: true

        working-directory: infra

      - name: Terraform Apply

        id: apply

        run: terraform apply --auto-approve

        continue-on-error: true

        working-directory: infra     

  
     
